### ISSUE TITLE
License missing from repo

### ISSUE THREAD

**Issue by karan** [cusspvz/openwrt-mt7601u#1]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by cusspvz** [comment]
Hi @karan ,

despite I've added a license, @kuba-moo 's mt7601 driver (a complete rewrite) was merged into kernel `4.2`, _OpenWRT_ build toolchain already has a `Makefile` for the _Raspberry PI_ (Since they use latest RPI kernel release), meaning this is deprecated as told on README.

Anyway, thanks for reporting the lack of LICENSE file. :)
